---
title: "UCD Week of SEISMIC Talk Figures 2023"
output: html_notebook
date: 2023-01-31
---

```{r setup}
#data import 
setwd("~/Documents/GitHub/curving-grades/")
source("curving_grades_datasets.R")

setwd("~/Documents/GitHub/curving-grades/")
source("curving_grades_functions.R")

#original survey and supplemental survey for NUT10, long format
nut10 <- lik_long

#this data created using curving_grades_datasets.R code 
```

# Demographics

```{r percent demographics}

  lik_long %>%
  distinct(sid, .keep_all = T) %>%
  summarise(n = n(),
            percent_women = (sum(GENDER == "F", na.rm = T)/n)*100,
            percent_urm = (sum(IS_URM == 1, na.rm = T)/n)*100,
            percent_transfer = (sum(is_xfer == TRUE,na.rm = T)/n)*100,
            percent_esl = (sum(ESL == "1",  na.rm = T)/n)*100, 
            percent_first_gen =  (sum(FIRST_GENERATION == "1",  na.rm = T)/n)*100,
            percent_low_income = (sum(LOW_INCOME == "1",  na.rm = T)/n)*100, 
            percent_international = (sum(STARTED_INTERNATIONAL == "1", na.rm = T)/n)*100,
            avg_gpa_prior = mean(UCD_OVERALL_GPA, na.rm = T)) %>%
  t()%>% #transpose
  as.data.frame() 
```

```{r class level by transfer status}
  lik_long %>%
  distinct(sid, .keep_all = T) %>% 
  count(CLASS_LEVEL, is_xfer) %>%
  mutate(perc = n/590) %>%
  mutate(CLASS_LEVEL = factor(CLASS_LEVEL, levels = c("FR","SO","JR","SR"))) %>%
  drop_na(CLASS_LEVEL) %>%
  ggplot(aes(x = CLASS_LEVEL, y = perc*100, fill = is_xfer)) + 
    geom_col(color = "black", size = 1) + 
    labs(x = "Class level", y = "Percent (%)", fill = NULL) +
    scale_fill_manual(values = c("white","#00CED1"), labels = c("First-Year start", "Transfer")) +
    theme_classic(base_size = 20) + 
    theme(
        plot.title = element_text(hjust = 0.5), 
        axis.text = element_text(color = "black"))

#first term at university by transfer
  lik_long %>%
  distinct(sid, .keep_all = T) %>% 
  mutate(first_term = ifelse(ADMIT_TERM == "202010", 1,0)) %>%
  mutate(first_term = replace_na(first_term, 0)) %>%
  count(CLASS_LEVEL, first_term, is_xfer) %>%
  mutate(perc = n/590) %>%
  mutate(CLASS_LEVEL = factor(CLASS_LEVEL, levels = c("FR","SO","JR","SR")),
         is_xfer = factor(is_xfer, labels = c("non-Transfer","Transfer"))) %>%
  drop_na(CLASS_LEVEL) %>%
  ggplot(aes(x = CLASS_LEVEL, y = perc*100, fill = as.factor(first_term))) + 
    geom_col(color = "black", size = 1) + 
    labs(x = "Class level", y = "Percent (%)", fill = "first term at university?") +
    scale_fill_manual(values = c("white","#00CED1"), labels = c("no", "yes")) +
    facet_wrap(~is_xfer) +
    theme_classic(base_size = 25) + 
    theme(
        plot.title = element_text(hjust = 0.5), 
        axis.text = element_text(color = "black"))
```

```{r percent in first year}
#what percent of students were in their first year at the university?
  lik_long %>%
  distinct(sid, .keep_all = T) %>% 
  count(ADMIT_TERM == "202010") %>% #fall 2020, the term the class was offered
  mutate(perc = n/590*100)
```

```{r STEM majors}
#STEM vs non-STEM majors
lik_long <- left_join(lik_long, majors_list)

lik_long %>%
  distinct(sid, .keep_all = T) %>% 
  count(STEM) %>%
  mutate(n_total = sum(n), 
         perc = n/n_total*100)
```

```{r demographics barplot for ppt}
  lik_long %>%
  distinct(sid, .keep_all = T) %>%
  summarise(Women = (sum(GENDER == "F", na.rm = T)/590)*100,
            PEER = (sum(IS_URM == 1, na.rm = T)/590)*100,
            FirstGen =  (sum(FIRST_GENERATION == "1",  na.rm = T)/590)*100,
            LowIncome = (sum(LOW_INCOME == "1",  na.rm = T)/590)*100,
            International = (sum(STARTED_INTERNATIONAL == "1", na.rm = T)/590)*100,
            Transfer = (sum(is_xfer == TRUE,na.rm = T)/590)*100,
            STEM_Major = (sum(STEM == "1", na.rm = T)/590)*100) %>%
  t() %>% #transpose
  as.data.frame() %>%
  rownames_to_column() %>%
  arrange(rowname) %>%
  mutate(rowname = factor(rowname, unique(rowname))) %>%
  mutate(rowname = relevel(rowname, ref = "Women")) %>%
  ggplot(aes(x = rowname, y= V1, fill = rowname)) + 
  geom_col() + 
  labs(x = NULL, y = "Percent (%)") + 
  geom_vline(xintercept = 5.5) + 
  theme_classic(base_size = 20) + 
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1))
  
```

# Overall Student Perceptions

```{r factor 1}
#factor 1 

factor1 <- c("Q57_9", "Q59_14", "Q57_7", "Q57_1", "Q57_5", "Q57_2")

factor1graph <-
nut10 %>%
  filter(question %in% factor1) %>%
  mutate(question = factor(question, levels = factor1)) %>%
  arrange(question) %>%
  ggplot(aes(x = question, y = score, fill = question)) + 
  stat_summary(geom = "col", color = "black", size = 1) + 
  stat_summary(geom = "errorbar", width = 0.5, size = 1) +  
  geom_hline(yintercept = 0, size = 1) + 
  scale_fill_brewer(labels = function(x) str_wrap(x, width = 50)) +
  labs(x = NULL, y =  NULL, fill = "Question") + 
  #scale_fill_discrete(labels = function(x) str_wrap(x, width = 20)) +
  ylim(-0.5, 1) + 
  theme_classic(base_size = 30) + 
  theme(legend.position = "none", 
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.line.x = element_blank(),
        axis.text.y = element_text(angle = 90, color = "black"))

factor1graph

#ggsave("~/Desktop/factor1graph.png", factor1graph, width = 7.25, height = 7.25, units = "in", dpi = 300)
```

```{r factor1 curving preference with time in university}
lik_long %>%
  distinct(sid, .keep_all = T) %>%
  filter(!is.na(ADMIT_TERM))%>%
ggplot(aes(x = ADMIT_TERM=="202010", y = factor1score, fill = ADMIT_TERM == "202010")) + 
  geom_boxplot() + 
  labs(x = "First Term at University?", y = "Average Likert Score (Factor 1)",
       fill = NULL) +
  scale_x_reverse(breaks = c(1,0), labels = c("Yes","No")) + 
  scale_fill_manual(values = c("white","#00CED1")) + 
  theme_classic(base_size = 14) + 
  theme(legend.position = "none")

#quick t-test
lik_long %>%
  distinct(sid, .keep_all = TRUE) %>%
  mutate(first_term = ifelse(ADMIT_TERM == "202010", 1, 0)) %>%
  t.test(.$factor1score ~ .$first_term, data = .)
```

```{r factor 2}
factor2 <- c("Q59_13", "Q57_4", "Q57_6", "Q59_11", "Q59_4")

factor2graph<-
nut10 %>%
    filter(question %in% factor2) %>%
    group_by(question,prompt) %>%
    summarise(n = n(), 
              mean_score = mean(score, na.rm = T), 
              se = std.error(score, na.rm = T)) %>%
  mutate(question = factor(question, levels = factor2)) %>%
  arrange(question) %>%
  ggplot(aes(x = question, y = mean_score, fill = question)) + 
  geom_col(color = "black", size = 1) + 
  geom_errorbar(aes(ymin = mean_score-se, ymax = mean_score+se), width = 0.5, size =1) +  
  geom_hline(yintercept = 0, size = 1) + 
  scale_fill_brewer(palette = "YlOrBr") +
  labs(x = NULL, y = NULL, fill = "Question") + 
  #scale_fill_discrete(labels = function(x) str_wrap(x, width = 20)) +
  ylim(-0.6, 0.5) + 
  theme_classic(base_size = 30) + 
  theme(legend.position = "none", 
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.line.x = element_blank(),
        axis.text.y = element_text(angle = 90, color = "black"))

#ggsave("~/Desktop/factor2graph.png", factor2graph, width = 5.9, height = 6, units = "in", dpi = 300)

```

```{r factor 3}
factor3 <- c("Q57_8", "Q57_12", "Q57_14")

factor3graph<-
nut10 %>%
    filter(question %in% factor3) %>%
    group_by(question,prompt) %>%
    summarise(n = n(), 
              mean_score = mean(score, na.rm = T), 
              se = std.error(score, na.rm = T)) %>%
  mutate(question = factor(question, levels = factor3)) %>%
  arrange(question) %>%
  ggplot(aes(x = question, y = mean_score, fill = question)) + 
  geom_col(color = "black", size = 1) + 
  geom_errorbar(aes(ymin = mean_score-se, ymax = mean_score+se), width = 0.5, size = 1) +  
  geom_hline(yintercept = 0, size = 1) + 
  scale_fill_brewer(palette = "Purples") +
  labs(x = NULL, y = NULL, fill = "Question") + 
  #scale_fill_discrete(labels = function(x) str_wrap(x, width = 20)) +
  ylim(-0.25, 1.25) + 
  theme_classic(base_size = 30) + 
  theme(legend.position = "none", 
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.line.x = element_blank(),
        axis.text.y = element_text(angle = 90, color = "black"))

#ggsave("~/Desktop/factor3graph.png", factor3graph, width = 4.75, height = 6, units = "in", dpi = 300)

```

# Perceptions by Curve Definitions

```{r curve defintions}
#what definition do most students hold of curving?
nut10 %>%
  group_by(curve_def) %>%
  distinct(sid) %>%
    tally() %>%
  mutate(perc = (n/283)*100)

#plot data 
plot_definitions <- 
nut10 %>%
  distinct(sid,.keep_all = T) %>%
  drop_na(curve_def) %>%
  group_by(curve_def) %>%
  tally() %>%
  #next two lines arrange the bars in order of sample size
  arrange(desc(n)) %>%
  mutate(curve_def = factor(curve_def, unique(curve_def))) %>%
  ggplot(aes(x = curve_def, y = (n/283)*100, #makes it a percent of total
             fill = curve_def)) +
  geom_col(color = "black") + 
  scale_fill_manual(values = c("ranked"= "salmon2", 
                               "scaled_avg" = "mediumpurple1", 
                               "scaled_pass" = "turquoise3", 
                               "Other" = "gray")) +
    theme_classic(base_size = 16)

#view plot
plot_definitions
  
  #format for export to powerpoint (vertical graph)
  plot_definitions + 
  labs(x = NULL, y = NULL) + 
  theme_classic(base_size = 30) + 
  theme(legend.position = "none", 
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.line.x = element_blank(),
        axis.text.y = element_text(angle = 90, color = "black"))

```

```{r curve def by STEM}
#curve definitions by STEM major
curvedef_by_stem <- 
lik_long %>%
  distinct(sid,.keep_all = T) %>%
  drop_na(curve_def) %>% #excludes students without curve definitions
  add_count(STEM, name = "n_STEM") %>% 
  group_by(STEM, curve_def) %>%
  summarise(n_stem = mean(n_STEM), 
            n = n()) %>%
  mutate(perc = n/n_stem*100) %>%
  mutate(curve_def = factor(curve_def, levels = c("scaled_avg","scaled_pass","ranked","Other"))) %>%
  ggplot(aes(x = curve_def, y = perc, fill = paste(STEM,curve_def,sep="_"), color = curve_def)) + 
  geom_col(position = position_dodge(0.9), size = 1) + 
    labs(x = NULL, y = "Percent (%)", fill = NULL) +
    scale_color_manual(values = c("ranked"= "salmon2", 
                               "scaled_avg" = "mediumpurple1", 
                               "scaled_pass" = "turquoise3", 
                               "Other" = "gray")) + 
  scale_fill_manual(values = c("white","white","white","white","gray","salmon2","mediumpurple1","turquoise3")) + 
    theme_classic(base_size = 18) + 
    theme(legend.position = "none",
        plot.title = element_text(hjust = 0.5), 
        axis.text = element_text(color = "black"))

#create a prettier legend

stem_legend <- cowplot::get_legend(
lik_long %>%
  count(STEM) %>%
  ggplot(aes(x = STEM, y = n, fill = as.factor(STEM)))+
  geom_col(color = "black")+ 
  scale_fill_manual(name = "Major", values = c("white","gray"), labels = c("non-STEM", "STEM")) +
  theme_classic(base_size = 18) 
) 

#cowplot with prettier legend
cowplot::plot_grid(curvedef_by_stem, stem_legend,
                   rel_widths = c(1,0.2))

#ready for powerpoint export (vertical)
curvedef_by_stem + 
    labs(x = NULL, y = NULL) + 
  theme_classic(base_size = 30) + 
  theme(legend.position = "none", 
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.line.x = element_blank(),
        axis.text.y = element_text(angle = 90, color = "black"))
```

```{r chi-sq for STEM majors}
#probability of scaled avg given STEM
prop.test(x = c(48,67), n = c(143,140))

#probability of scaled pass given STEM
prop.test(x = c(55,31), n = c(143,140))

```

```{r factor 1 by curve_def}

def_colors = c("salmon2", "mediumpurple1", "turquoise3")
def_xlabs = c("ranked", "scaled to avg", "scaled so most pass")
#factor 1

fac1_bydef <-
nut10 %>%
  filter(curve_def != "Other" & !is.na(curve_def)) %>%
  filter(question %in% factor1) %>%
  drop_na(score) %>%
  group_by(sid) %>%
  mutate(factor1score = mean(score)) %>% #verified that this uses the group_by sid to "summarise" for each individual 
  ungroup() %>%
  distinct(sid, .keep_all = TRUE) %>%
  ggplot(aes(x = curve_def, y = factor1score, fill = curve_def)) + 
  stat_summary(geom = "col", color = "black", size = 1) + 
  stat_summary(geom = "errorbar", width = 0.5, size = 1) +  
  geom_signif(y_position=0.81, xmin=1, xmax=2,
              annotation=c("*"), tip_length = 0.01, textsize = 8, size = 1)  + 
    geom_hline(yintercept = 0, size = 1) +
  scale_fill_manual(values = def_colors) + 
  scale_x_discrete(labels = function(x) str_wrap(def_xlabs, width = 10)) + 
  labs(x =  NULL, y = "Average Likert score") + 
  theme_classic(base_size = 20)  + 
  theme(legend.position = "none",
        plot.title = element_text(hjust = 0.5), 
        axis.text = element_text(color = "black"))
```

```{r t-tests: factor1 by curving definition}
nut10 %>%
  filter(curve_def != "Other" & !is.na(curve_def)) %>%
  filter(question %in% factor1) %>%
  drop_na(score) %>%
  group_by(sid) %>%
  mutate(factor1score = mean(score)) %>% #verified that this uses the group_by sid to "summarise" for each individual 
  ungroup() %>%
  distinct(sid, .keep_all = TRUE) %>%
  pairwise.t.test(.$factor1score, .$curve_def, p.adj = "bonf", data = .)

```

```{r factor2 by curve_def}
nut10 %>%
  filter(curve_def != "Other" & !is.na(curve_def)) %>%
  filter(question %in% factor2) %>%
  drop_na(score) %>%
  group_by(sid) %>%
  mutate(factor2score = mean(score)) %>% #verified that this uses the group_by sid to "summarise" for each individual 
  ungroup() %>%
  distinct(sid, .keep_all = TRUE) %>%
  ggplot(aes(x = curve_def, y = factor2score, fill = curve_def)) + 
  stat_summary(geom = "col", color = "black", size = 1) + 
  stat_summary(geom = "errorbar", width = 0.5, size = 1) + 
  geom_signif(y_position=0.21, xmin=1, xmax=2,
              annotation=c("*"), tip_length = 0.01, textsize = 8, size = 1) + 
  geom_hline(yintercept = 0, size = 1) +
  scale_fill_manual(values = def_colors) + 
  scale_x_discrete(labels = function(x) str_wrap(def_xlabs, width = 10)) + 
  labs(x = NULL, y = "Average Likert score") + 
  theme_classic(base_size = 20)  + 
  theme(legend.position = "none", 
        plot.title = element_text(hjust = 0.5),
        axis.text = element_text(color = "black"))
```

```{r t-tests: factor2 by curving definition}
nut10 %>%
  filter(curve_def != "Other" & !is.na(curve_def)) %>%
  filter(question %in% factor2) %>%
  drop_na(score) %>%
  group_by(sid) %>%
  mutate(factor2score = mean(score)) %>% #verified that this uses the group_by sid to "summarise" for each individual 
  ungroup() %>%
  distinct(sid, .keep_all = TRUE) %>%
  pairwise.t.test(.$factor2score, .$curve_def, p.adj = "bonf", data = .)

```

```{r preference by curve_def}
#preference question alone
#Q57_7: "I prefer classes that curve student grades to those that do not curve."

nut10 %>%
  filter(curve_def != "Other" & !is.na(curve_def)) %>%
  filter(question == "Q57_7") %>%
  drop_na(score) %>%
  distinct(sid, .keep_all = TRUE) %>%
  ggplot(aes(x = curve_def, y = score, fill = curve_def)) + 
  stat_summary(geom = "col", color = "black", size = 1) + 
  stat_summary(geom = "errorbar", width = 0.5, size = 1) +  
    geom_hline(yintercept = 0, size = 1) +
  scale_fill_manual(values = def_colors) + 
  scale_x_discrete(labels = function(x) str_wrap(def_xlabs, width = 10)) + 
  labs(x =  NULL, y = "Average Likert score") + 
  theme_classic(base_size = 20)  + 
  theme(legend.position = "none",
        plot.title = element_text(hjust = 0.5), 
        axis.text = element_text(color = "black"))
```

# Test Anxiety and Curving

```{r test anxiety summary stats}

#average scores for each question 
lik_long %>%
  filter(question %in% anxietyQs) %>%
  group_by(question, prompt) %>%
  drop_na(score) %>%
  summarise(n = n(),
            mean_score = mean(score),
            se_score = std.error(score),
            median_score = median(score)) 
```

```{r test anxiety raw scores for ppt}
lik_long %>%
  filter(question %in% anxietyQs) %>%
  mutate(question = factor(question, levels = anxietyQs)) %>%
  arrange(question) %>%
  ggplot(aes(x = question, y = score, fill = question)) + 
  stat_summary(geom = "col", color = "black", size = 1) + 
  stat_summary(geom = "errorbar", width = 0.5, size = 1) +  
  geom_hline(yintercept = 0, size = 1) + 
  scale_fill_brewer(labels = function(x) str_wrap(x, width = 50)) +
  labs(x = NULL, y =  NULL, fill = "Question") + 
  #scale_fill_discrete(labels = function(x) str_wrap(x, width = 20)) +
  theme_classic(base_size = 30) + 
  theme(legend.position = "none", 
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.line.x = element_blank(),
        axis.text.y = element_text(angle = 90, color = "black"))
```

```{r categorical var anxiety}
hist(lik_long$test_anxiety) 

lik_long %>%
  distinct(sid, .keep_all = T) %>%
ggplot(aes(x = test_anxiety)) + 
  geom_histogram(binwidth = 4, color = "black",fill = "white") + 
  xlim(-16,16) + 
  labs(x = "Test anxiety \n(average across 8 items)", y = "Count") + 
  theme_classic(base_size = 20)

#create 4 "categories" of anxiety
#1 = no to low, #2 = mild, #3 = moderate, #4 = high
lik_long$test_anx_cat <- cut(lik_long$test_anxiety, breaks = c(-16,-12,-4,4,12,16), ordered_result = TRUE)
hist(as.numeric(lik_long$test_anx_cat))
```

```{r factor1 by catagorical test_anxiety}
lik_long %>%
  group_by(sid) %>%
  mutate(factor1score = sum(score[question %in% factor1], na.rm = T)) %>% 
  ungroup() %>%
  filter(GENDER != "N" & !is.na(GENDER)) %>%
  ggplot( aes(x = as.factor(test_anx_cat), y = factor1score, fill = test_anx_cat)) + 
  geom_boxplot() + 
  scale_x_discrete(labels = c("low", "mild", "moderate", "high", "severe")) + 
  labs(x = "Test Anxiety Category", y = "Average Likert Score \n(Factor1)") + 
  theme_classic(base_size = 20) + 
  theme(legend.position = "none")

#confirm no significant differences with ANOVA
lik_long %>%
  distinct(sid, .keep_all = T) %>%
  lm(factor1score ~ test_anx_cat, data = .) %>%
  anova()
```
```{r factor1 by gender}
lik_long %>%
  filter(GENDER != "N" & !is.na(GENDER)) %>%
  ggplot( aes(x = GENDER, y = factor1score, fill = GENDER)) + 
  geom_boxplot() + 
  labs(x = "Gender", y = "Average Likert Score \n(Factor1)") + 
  scale_fill_manual(values = c("purple", "orange")) + 
  theme_classic(base_size = 20) + 
  theme(legend.position = "none")

#quick t-test
lik_long %>%
  filter(GENDER != "N" & !is.na(GENDER)) %>%
  distinct(sid, .keep_all = TRUE) %>%
  t.test(.$factor1score ~ .$GENDER, data = .)
```